server:
  port: 8900
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  routes:
    services-default.path: /services/compute/**
    services-default.serviceId: compute-service

